# SIEAN IVAR B. CORPORAL | 2ECE-A

## POSITIONAL AND LABEL-BASED SLICING

In [3]:
import pandas as pd
cars = pd.read_csv('cars.csv')
cars

print("Shape of the dataframe cars: ", cars.shape)
print("\nThe column names of cars: \n\n", cars.columns.tolist(), "\n")

cars_6_to_10 = cars.iloc[5:10]
cars_6_to_10.loc[:, ['Model', 'mpg', 'cyl', 'hp', 'gear']]

Shape of the dataframe cars:  (32, 12)

The column names of cars:

 ['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

##  MODEL LOOKUP

In [63]:
import pandas as pd
cars=pd.read_csv('cars.csv')
cars

toyota = cars[cars['Model'] == 'Toyota Corolla']
pontiac = cars[cars['Model'] == 'Pontiac Firebird']

display(toyota)
display(pontiac.loc[:, ['Model', 'mpg', 'hp', 'wt']])

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

## MULTI-MODEL SUBSETTING

In [78]:
import pandas as pd
cars=pd.read_csv('cars.csv')
cars

selected_cars = cars[(cars['Model'] == 'Datsun 710') | (cars['Model'] == 'Lotus Europa') | (cars['Model'] == 'Ferrari Dino')]
selected_cars = selected_cars.loc[:, ['Model', 'mpg', 'cyl', 'hp', 'gear']]

print("The shape of the selected cars is: ", selected_cars.shape, "\n")
display(selected_cars)

The shape of the selected cars is:  (3, 5)

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5